// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

// Importa la clase fundamental FirebaseOptions, necesaria para la configuración.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

// Importa utilidades de la librería 'flutter/foundation' para determinar
// la plataforma de ejecución.
import 'package:flutter/foundation.dart'
        // defaultTargetPlatform: Variable que identifica la plataforma nativa (iOS, Android, etc.).
        // kIsWeb: Bandera booleana para saber si la aplicación se ejecuta en un navegador.
        // TargetPlatform: Enumeración que lista las plataformas objetivo.
        show
        defaultTargetPlatform,
        kIsWeb,
        TargetPlatform;

/// Opciones predeterminadas ([FirebaseOptions]) para usar con tus aplicaciones de Firebase.
///
/// Esta clase es generada automáticamente por FlutterFire CLI y proporciona
/// la configuración específica de Firebase para cada plataforma (Web, Android, iOS, etc.).
class DefaultFirebaseOptions {
  /// Retorna las [FirebaseOptions] adecuadas para la plataforma actual.
  ///
  /// Utiliza `kIsWeb` y `defaultTargetPlatform` para determinar qué
  /// conjunto de opciones estáticas debe ser devuelto (ej. `web`, `android`, `ios`).
  static FirebaseOptions get currentPlatform {
    // Si la aplicación se está ejecutando en un navegador web, retorna las opciones 'web'.
    if (kIsWeb) {
      return web;
    }

    // Comprueba la plataforma nativa actual usando un switch.
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android; // Opciones para Android
      case TargetPlatform.iOS:
        return ios; // Opciones para iOS
      case TargetPlatform.macOS:
        return macos; // Opciones para macOS
      case TargetPlatform.windows:
        return windows; // Opciones para Windows
      case TargetPlatform.linux:
        // Lanza un error si Linux no está configurado (instrucción de la CLI de FlutterFire).
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        // Lanza un error si la plataforma actual no es compatible o reconocida.
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Opciones de Firebase para la plataforma Web.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChocQ0kIhQNBu90CPgt03S0K6pAWWX9B0',
    appId: '1:48438092452:web:a9ebdcf9783b943e537c31',
    messagingSenderId: '48438092452',
    projectId: 'moviemood-ee4c9',
    authDomain: 'moviemood-ee4c9.firebaseapp.com',
    storageBucket: 'moviemood-ee4c9.firebasestorage.app',
    measurementId: 'G-1P1P7Q66FB',
  );

  /// Opciones de Firebase para la plataforma Android.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4Wpa_oSyF5Sre11fGVQWNxf9fdhLE9qw',
    appId: '1:48438092452:android:0cc75b6368a0a4e0537c31',
    messagingSenderId: '48438092452',
    projectId: 'moviemood-ee4c9',
    storageBucket: 'moviemood-ee4c9.firebasestorage.app',
    // Los campos 'authDomain' y 'measurementId' no son necesarios para Android.
  );

  /// Opciones de Firebase para la plataforma iOS (No aplica).
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqBQtPsQmTiGT6yS_aoo4RDbocttGaaF4',
    appId: '1:48438092452:ios:aa4cb15a4e029199537c31',
    messagingSenderId: '48438092452',
    projectId: 'moviemood-ee4c9',
    storageBucket: 'moviemood-ee4c9.firebasestorage.app',
    iosBundleId:
        'com.example.flutterApplication1', // ID de Bundle de la aplicación iOS.
  );

  /// Opciones de Firebase para la plataforma MacOOS (No aplica en este caso)
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqBQtPsQmTiGT6yS_aoo4RDbocttGaaF4',
    appId: '1:48438092452:ios:aa4cb15a4e029199537c31',
    messagingSenderId: '48438092452',
    projectId: 'moviemood-ee4c9',
    storageBucket: 'moviemood-ee4c9.firebasestorage.app',
    iosBundleId:
        'com.example.flutterApplication1', // ID de Bundle de la aplicación macOS.
  );

  /// Opciones de Firebase para la plataforma Windows
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChocQ0kIhQNBu90CPgt03S0K6pAWWX9B0',
    appId:
        '1:48438092452:web:ab7a63eda31b04af537c31', // Puede usar un App ID de tipo Web.
    messagingSenderId: '48438092452',
    projectId: 'moviemood-ee4c9',
    authDomain: 'moviemood-ee4c9.firebaseapp.com',
    storageBucket: 'moviemood-ee4c9.firebasestorage.app',
    measurementId: 'G-JE3XXQSYNQ',
  );
}
